
export default {
  serverError: 'Đã xảy ra lỗi, vui lòng thử lại!',
  noPermission: 'Bạn không có quyền thực hiện hành động này!',
  userBanned: 'Tài khoản của bạn đã bị khoá!',
  name: 'Tên',
  desc: 'Mô tả',
  title: 'Tiêu đề',
  cover: 'Ảnh',
  category: 'Danh mục',
  active: 'Active',
  price: 'Giá',
  discountPercent: 'Giảm giá',
  quantity: 'Số lượng',
  notifyWhenQuantityBelow: 'TB khi số lượng dưới',
  password: 'Mật khẩu',
  email: 'Email',
  phone: 'SĐT',
  address: 'Địa chỉ',
  content: 'Nội dung',
  product: 'Sản phẩm',
  create: 'Tạo',
  update: 'Cập nhật',
  status: 'Trạng thái',
  login: 'Đăng nhập',
  register: 'Đăng ký',
  username: 'Tên đăng nhập',
  passwordRequired: 'Mật khẩu không được trống',
  usernameRequired: 'Tên đăng nhập không được trống',
  passwordConfirm: 'Xác nhận mật khẩu',
  passwordConfirmRequired: 'Xác nhận mật khẩu không được trống',
  emailRequired: 'Email không được trống',
  phoneRequired: 'SĐT không được trống',
  alreadyHaveAccount: 'Bạn đã có tài khoản',
  dontHaveAccount: 'Bạn chưa có tài khoản',
  orderSuccess: 'Đặt hàng thành công',
  orderSuccessContent: 'Đơn hàng của bạn đang được chúng tối xác nhận!',
  continue: 'Tiếp tục mua hàng',
  search: 'Tìm kiếm',
}
